import React from "react";
import Nav from "./Nav";
import Footer from "./Footer";
import { useRouter } from "next/router";
import Head from "next/head";

const Layout: React.FC<{ children: JSX.Element | React.ReactNode }> = ({
  children,
}) => {
  const { pathname } = useRouter();

  return (
    <>
      <Head>
        <title>Rik Academy</title>
        <meta name="description" content="Generated by Rik Academy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Nav />
      <main className={`${pathname !== "/" ? "mt-[79px] lg:mt-[93px]" : ""}`}>
        {children}
      </main>
      {!pathname.includes("login") && <Footer />}
    </>
  );
};

export default Layout;
